name: PR Labeler

on:
  pull_request_target:
    branches:
      - dev
      - stg
      - stg1
      - main
    types:
      - opened
      - reopened
      - synchronize
      - edited
    paths:
      - '**'

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - uses: actions/labeler@v5
        with:
          sync-labels: true
          repo-token: ${{ steps.app-token.outputs.token }}
