name: PR Release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/pr-release.yml'
      - '**'

jobs:
  git-pr-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [dev, stg]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
      - run: gem install --no-document git-pr-release
      - run: git-pr-release
        env:
          GIT_PR_RELEASE_TITLE: "[Terraform] ${{ steps.vars.outputs.branch_name }} (${{ matrix.target }})"
          GIT_PR_RELEASE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_PR_RELEASE_BRANCH_PRODUCTION: ${{ matrix.target }}
          GIT_PR_RELEASE_BRANCH_STAGING: main
          GIT_PR_RELEASE_LABELS: pr-release-${{ matrix.target }}
          GIT_PR_RELEASE_TEMPLATE: .github/workflows/git-pr-release-template.erb
          TZ: Asia/Tokyo
